version: 0.0
os: linux
files:
  - source: /
    destination: /myapp
permissions:
  - object: /myapp/startApp.sh
    mode: 777
  - object: /myapp/stopApp.sh
    mode: 777
#don't know why below were commented out, i tried uncommented it, the application did started, but CodeDeploy stuck waiting why?
#i think i know why, once the startApp.sh is called, there is no one going to stop it so subsequent startApp.sh returns error
#see: http://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-example.html
#maybe i need a ValidateService: hook?? but the status seems to be that it stuck at ApplicationStart without any advancement why?
hooks:
  ApplicationStart:
    #- location: stopApp.sh
    #  timeout: 10
    - location: startApp.sh
      timeout: 10
